export const DEFAULT_MARKET_CATALOG = [
  {
    symbol: "RELIANCE",
    alphaSymbol: "RELIANCE.BSE",
    name: "Reliance Industries",
    sector: "Energy",
    marketCapBand: "large_cap",
    basePrice: 2450,
    baseVolatility: 0.024,
    description: "Oil-to-retail conglomerate with a major consumer footprint.",
  },
  {
    symbol: "TCS",
    alphaSymbol: "TCS.BSE",
    name: "Tata Consultancy Services",
    sector: "IT Services",
    marketCapBand: "large_cap",
    basePrice: 3800,
    baseVolatility: 0.018,
    description: "Large-cap IT services exporter with global enterprise clients.",
  },
  {
    symbol: "INFY",
    alphaSymbol: "INFY.BSE",
    name: "Infosys",
    sector: "IT Services",
    marketCapBand: "large_cap",
    basePrice: 1550,
    baseVolatility: 0.022,
    description: "IT consulting major with strong digital transformation exposure.",
  },
  {
    symbol: "HDFCBANK",
    alphaSymbol: "HDFCBANK.BSE",
    name: "HDFC Bank",
    sector: "Banking",
    marketCapBand: "large_cap",
    basePrice: 1680,
    baseVolatility: 0.018,
    description: "Private sector banking leader with broad retail reach.",
  },
  {
    symbol: "ICICIBANK",
    alphaSymbol: "ICICIBANK.BSE",
    name: "ICICI Bank",
    sector: "Banking",
    marketCapBand: "large_cap",
    basePrice: 1120,
    baseVolatility: 0.021,
    description: "Diversified private bank with corporate and retail lending exposure.",
  },
  {
    symbol: "SBIN",
    alphaSymbol: "SBIN.BSE",
    name: "State Bank of India",
    sector: "Banking",
    marketCapBand: "large_cap",
    basePrice: 780,
    baseVolatility: 0.028,
    description: "India's largest public sector bank with strong deposit franchise.",
  },
  {
    symbol: "BHARTIARTL",
    alphaSymbol: "BHARTIARTL.BSE",
    name: "Bharti Airtel",
    sector: "Telecom",
    marketCapBand: "large_cap",
    basePrice: 1450,
    baseVolatility: 0.019,
    description: "Telecom and digital services leader with recurring consumer demand.",
  },
  {
    symbol: "ITC",
    alphaSymbol: "ITC.BSE",
    name: "ITC",
    sector: "FMCG",
    marketCapBand: "large_cap",
    basePrice: 440,
    baseVolatility: 0.015,
    description: "Consumer staples giant spanning FMCG, hotels, and paperboards.",
  },
  {
    symbol: "TATASTEEL",
    alphaSymbol: "TATASTEEL.BSE",
    name: "Tata Steel",
    sector: "Metals",
    marketCapBand: "large_cap",
    basePrice: 165,
    baseVolatility: 0.034,
    description: "Cyclical steel producer tied to industrial demand and commodity moves.",
  },
  {
    symbol: "LT",
    alphaSymbol: "LT.BSE",
    name: "Larsen & Toubro",
    sector: "Infrastructure",
    marketCapBand: "large_cap",
    basePrice: 3650,
    baseVolatility: 0.02,
    description: "Infrastructure and engineering major benefiting from capex cycles.",
  },
  {
    symbol: "MARUTI",
    alphaSymbol: "MARUTI.BSE",
    name: "Maruti Suzuki",
    sector: "Auto",
    marketCapBand: "large_cap",
    basePrice: 11800,
    baseVolatility: 0.017,
    description: "Passenger vehicle leader with broad domestic market share.",
  },
  {
    symbol: "SUNPHARMA",
    alphaSymbol: "SUNPHARMA.BSE",
    name: "Sun Pharma",
    sector: "Pharma",
    marketCapBand: "large_cap",
    basePrice: 1650,
    baseVolatility: 0.019,
    description: "Pharma exporter with specialty and chronic therapy portfolio.",
  },
  {
    symbol: "ASIANPAINT",
    alphaSymbol: "ASIANPAINT.BSE",
    name: "Asian Paints",
    sector: "Consumer",
    marketCapBand: "large_cap",
    basePrice: 2900,
    baseVolatility: 0.016,
    description: "Defensive consumer brand with strong distribution and margins.",
  },
  {
    symbol: "BAJFINANCE",
    alphaSymbol: "BAJFINANCE.BSE",
    name: "Bajaj Finance",
    sector: "NBFC",
    marketCapBand: "large_cap",
    basePrice: 6900,
    baseVolatility: 0.027,
    description: "High-growth NBFC focused on consumer and SME lending.",
  },
  {
    symbol: "ADANIPORTS",
    alphaSymbol: "ADANIPORTS.BSE",
    name: "Adani Ports",
    sector: "Logistics",
    marketCapBand: "large_cap",
    basePrice: 1280,
    baseVolatility: 0.031,
    description: "Port and logistics operator with infrastructure-linked earnings.",
  },
];
